package br.com.sgejs.modelo.rh.servidor.enums;

public enum Instrucao {

    NAO_APLICA,
    NAO_ALFABETIZADO,
    PRIMARIO_INCOMPLETO,
    PRIMARIO_COMPLETO,
    GINASIO_INCOMPLETO,
    GINASIO_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO;
}
